#!/bin/bash
#SBATCH -n 8
#SBATCH --mem 48G
#SBATCH -p mlow
#SBATCH --gres gpu:1
#SBATCH -o logs/svm/svm_%u_%j.out
#SBATCH -e logs/svm/svm_%u_%j.err

python svm_part1.py --svm_config configs/svm_configs/SVM_C_7_10_sweep_ImgSize_16.json --n_jobs 8
