#!/bin/bash
#SBATCH -n 4
#SBATCH --mem 16G
#SBATCH -p mlow
#SBATCH --gres gpu:1
#SBATCH -o logs/baseline_robust_%u_%j.out
#SBATCH -e logs/baseline_robust_%u_%j.err

python main.py --config configs/config_baseline.json
