#!/bin/bash
#SBATCH -n 4
#SBATCH --mem 24G
#SBATCH -p mlow
#SBATCH --gres gpu:1
#SBATCH -o logs/baselinepatch%u_%j.out
#SBATCH -e logs/baselinepatch%u_%j.err

python main_part2.py --config configs/patch_configs/config_best_so_far_patches.json