#!/bin/bash
#SBATCH -n 4
#SBATCH --mem 24G
#SBATCH -p mhigh
#SBATCH --gres gpu:1
#SBATCH -o logs/baselinepatch%u_%j.out
#SBATCH -e logs/baselinepatch%u_%j.err

python run_sweep.py --config configs/patch_configs/sweep_patching_1.json