#!/bin/bash
#SBATCH -n 4
#SBATCH --mem 24G
#SBATCH -p mhigh
#SBATCH --gres gpu:1
#SBATCH -o logs/bow_%u_%j.out
#SBATCH -e logs/bow_%u_%j.err

python main.py --config configs/squeeze_net/squeeze_net.yaml