#!/bin/bash
#SBATCH -n 4
#SBATCH --mem 24G
#SBATCH -p mlow
#SBATCH --gres gpu:1
#SBATCH -o logs/sweep_%u_%j.out
#SBATCH -e logs/sweep_%u_%j.err

SWEEP_ID=$1
COUNT=$2

if [ -z "$SWEEP_ID" ]; then
  echo "Error: No sweep ID provided."
  echo "Usage: sbatch job_hyp <SWEEP_ID> [COUNT]"
  exit 1
fi

# Ensure wandb is available (if using miniconda, activate env)
source /ghome/group04/miniconda3/etc/profile.d/conda.sh
conda activate c3

if [ -z "$COUNT" ]; then
    echo "Starting WandB agent for sweep: $SWEEP_ID (Unlimited runs until timeout)"
    wandb agent c3-team4/week3-hyperparameter-optimization/$SWEEP_ID
else
    echo "Starting WandB agent for sweep: $SWEEP_ID (Limit: $COUNT runs)"
    wandb agent --count $COUNT c3-team4/week3-hyperparameter-optimization/$SWEEP_ID
fi
