#!/bin/bash
#SBATCH -n 4
#SBATCH --mem 24G
#SBATCH -p mhigh
#SBATCH --gres gpu:1
#SBATCH -o logs/aug_%u_%j.out
#SBATCH -e logs/aug_%u_%j.err

python main_aug.py --config configs/data_augmentation2.json